GEN='../bin/bi'
all:
	$(GEN) demostruct.go > demostruct_gen.go
	$(GEN) embedded.go > embedded_gen.go
	$(GEN) embedded2.go > embedded2_gen.go
	$(GEN) slice.go > slice_gen.go

clean:
	/bin/rm *_gen.go

